# Generated by Django 5.0.5 on 2024-06-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_company_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewaspectsentiment',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
    ]
