# Generated by Django 5.0.5 on 2024-06-10 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_reviewaspectsentiment_is_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewaspectsentiment',
            name='aspect',
            field=models.CharField(choices=[('rasa', 'rasa'), ('tempat', 'tempat'), ('harga', 'harga'), ('pelayanan', 'pelayanan')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Aspect',
        ),
    ]
