# Generated by Django 5.0.5 on 2024-06-11 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_reviewaspectsentiment_aspect_delete_aspect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='user_to_company',
        ),
    ]
