# Generated by Django 5.0.5 on 2024-06-11 14:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_remove_company_user_to_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictedReviewAspectSentiment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('aspect', models.CharField(choices=[('rasa', 'rasa'), ('tempat', 'tempat'), ('harga', 'harga'), ('pelayanan', 'pelayanan')], max_length=50, null=True)),
                ('sentiment', models.IntegerField(choices=[(-1, 'Negatif'), (0, 'Netral'), (1, 'Positif')])),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_aspect', to='content.review')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RealReviewAspectSentiment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('aspect', models.CharField(choices=[('rasa', 'rasa'), ('tempat', 'tempat'), ('harga', 'harga'), ('pelayanan', 'pelayanan')], max_length=50, null=True)),
                ('sentiment', models.IntegerField(choices=[(-1, 'Negatif'), (0, 'Netral'), (1, 'Positif')])),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_review_aspect', to='content.review')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ReviewAspectSentiment',
        ),
    ]
