# Generated by Django 5.0.5 on 2024-06-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_predictedreviewaspectsentiment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictedreviewaspectsentiment',
            name='span',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
