# Generated by Django 5.0.5 on 2024-06-12 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_predictedreviewaspectsentiment_span'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_predict_fail',
            field=models.BooleanField(default=False),
        ),
    ]
